<a href="https://colab.research.google.com/github/anhtel94/CAP4630---Machine-Learning/blob/master/HW_4/HW4_problem2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import math

def maxpooling2d_prime(input_mat, s):
  input_size = len(input_mat)
  if s > input_size:
    raise Exception('Size of input matrix must bigger than s')
  size = math.ceil(input_size / s)
  output_mat = np.zeros((size, size))

  for i in range(size):
    for j in range(size):
      ##print(input_mat[i:(i+s), j:(j+s)])
      output_mat[i][j] = np.max([input_mat[(i*s):(i*s+s), (j*s):(j*s+s)]])
  return output_mat

input_size = int(input("Enter size n of input matrix (n x n):"))
input_mat = []
print("Enter the entires input matrix (by row-then-column order):")
for i in range(input_size):
  a = []
  for j in range(input_size):
    a.append(int(input()))
  input_mat.append(a)

print(np.array(input_mat))

s = int(input("Enter size s:"))

print(s)

print(maxpooling2d_prime(np.array(input_mat), s))

Enter size n of input matrix (n x n):6
Enter the entires input matrix (by row-then-column order):
1
2
1
2
4
5
2
4
2
1
0
3
1
2
4
2
4
5
2
1
2
1
2
1
1
1
2
3
1
2
1
1
2
3
1
2
[[1 2 1 2 4 5]
 [2 4 2 1 0 3]
 [1 2 4 2 4 5]
 [2 1 2 1 2 1]
 [1 1 2 3 1 2]
 [1 1 2 3 1 2]]
Enter size s:2
2
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
