<a href="https://colab.research.google.com/github/anhtel94/CAP4630---Machine-Learning/blob/master/HW_4/HW4_problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem 1**

In [44]:
import numpy as np

def conv2d_prime(input_mat, kernal_mat):
  filter = len(kernal_mat)
  size = len(input_mat) - len(kernal_mat) + 1
  output_mat = np.zeros((size, size))

  for i in range(size):
    for j in range(size):
      output_mat[i][j] = sum(sum(np.multiply(input_mat[i:(i+filter),j:(j+filter)], kernal_mat)))
  return output_mat

input_size = int(input("Enter size n of input matrix (n x n):"))
input_mat = []
print("Enter the entires input matrix (by row-then-column order):")
for i in range(input_size):
  a = []
  for j in range(input_size):
    a.append(int(input()))
  input_mat.append(a)

print(np.array(input_mat))

kernal_size = int(input("Enter size n of kernal matrix (m x m):"))
kernal_mat = []

if kernal_size > input_size:
  raise Exception('Size of input matrix must bigger than kernal matrix')

print("Enter the entires kernal matrix (by row-then-column order):")
for i in range(kernal_size):
  b = []
  for j in range(kernal_size):
    b.append(int(input()))
  kernal_mat.append(b)

print(np.array(kernal_mat))

print(conv2d_prime(np.array(input_mat),np.array(kernal_mat)))

Enter size n of input matrix (n x n):6
Enter the entires input matrix (by row-then-column order):
0
1
2
3
4
5
0
1
2
3
4
5
0
1
2
3
4
5
0
1
2
3
4
5
0
1
2
3
4
5
0
1
2
3
4
5
[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]
Enter size n of kernal matrix (m x m):3
Enter the entires kernal matrix (by row-then-column order):
1
1
1
1
1
1
1
1
1
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 9. 18. 27. 36.]
 [ 9. 18. 27. 36.]
 [ 9. 18. 27. 36.]
 [ 9. 18. 27. 36.]]
