<a href="https://colab.research.google.com/github/anhtel94/CAP4630---Machine-Learning/blob/master/HW_1/multiply_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 2: multiply_matrices

 Matrix A shape(m, n) and matrix B shape(i, j) are able to product and form matrix C shape(m, j) if and only if n = i and both A and B are not empty.

$$
\begin{bmatrix} 
a_11 & \cdots & a_1n \\
\vdots & \ddots & \vdots \\
a_m1 & \cdots & a_mn
\end{bmatrix}
*
\begin{bmatrix} 
b_11 & \cdots & b_1j \\
\vdots & \ddots & \vdots \\
b_i1 & \cdots & b_ij
\end{bmatrix}
=
\begin{bmatrix} 
c_11 & \cdots & c_1j \\
\vdots & \ddots & \vdots \\
c_m1 & \cdots & c_mj
\end{bmatrix}
$$

Coding part:

In [22]:
import numpy as np

# Create arrays for testing coding part
# Array A shape (4, 3) of random numbers 0-9
A = np.random.randint(0, 10, (4, 3))
print('Matrix A is:\n', A)

# Array B shape (3,5) of random numbers 0-9
B = np.random.randint(0, 10, (3,5))
print('Matrix B is:\n', B)

# Array C shape (4, 3) of random numbers 0-9
C = np.random.randint(0, 10, (4, 3))
print('Matrix C is:\n', C)

# Array D is an empty array
D = np.empty((0,0))
print('Matrix D is an empty array.')

# Function check if 2 matrices can be product
def multiply_matrices(A, B):
  # Check if A or B is an empty matrix
  if A.size == 0:
    raise Exception('These two matrices are incompatible, at least one is empty!')
    return
  elif B.size == 0:
    raise Exception('These two matrices are incompatible, at least one is empty!')
    return
  else:
    # Number of A's columns
    Ac = A.shape[1] 
    # Number of B's rows
    Br = B.shape[0]
  # Check if number of columns of A is equal number of rows of B
  if Ac == Br:
    # Number of A's rows
    Ar = A.shape[0]
    # Number of B's columns
    Bc = B.shape[1]

    C = np.zeros((Ar, Bc))
    r = 0
    c = 0
    # Loop through matrix C to calculate each element
    # Loop through rows
    for val1 in C:
      if r == Ar:
        break
      # Loop through columns
      for val2 in C[0]:
        C[r,c] = sum(np.multiply(A[r],B[:Bc, c]))
        c = c + 1
        if c == Bc:
          c = 0
          r = r + 1
          continue
  else:
    raise Exception('These two matrices are incompatible, number of columns in first matrix is different than number of rows in second matrix!')
  return C

  
# Testing 2 compatible matrices
print('A * B = \n', multiply_matrices(A, B))
# Testing 2 incompatible matrices with different size
multiply_matrices(A,C)
# Testing 2 incompatible matrices with one is empty matrix
multiply_matrices(A,D)

Matrix A is:
 [[2 4 6]
 [0 0 8]
 [5 4 4]
 [0 0 3]]
Matrix B is:
 [[1 7 8 6 7]
 [9 2 7 4 0]
 [7 5 4 2 8]]
Matrix C is:
 [[2 0 9]
 [7 0 2]
 [6 2 2]
 [3 0 3]]
Matrix D is an empty array.
Size of D =  0
A * B = 
 [[80. 52. 68. 40. 62.]
 [56. 40. 32. 16. 64.]
 [69. 63. 84. 54. 67.]
 [21. 15. 12.  6. 24.]]


Exception: ignored