<a href="https://colab.research.google.com/github/anhtel94/CAP4630---Machine-Learning/blob/master/HW_1/multiply_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 2: multiply_matrices

 Matrix A shape(m, n) and matrix B shape(i, j) are able to product and form matrix C shape(m, j) if and only if n = i and both A and B are not empty.

$$
\begin{bmatrix} 
a_11 & \cdots & a_1n \\
\vdots & \ddots & \vdots \\
a_m1 & \cdots & a_mn
\end{bmatrix}
*
\begin{bmatrix} 
b_11 & \cdots & b_1j \\
\vdots & \ddots & \vdots \\
b_i1 & \cdots & b_ij
\end{bmatrix}
=
\begin{bmatrix} 
c_11 & \cdots & c_1j \\
\vdots & \ddots & \vdots \\
c_m1 & \cdots & c_mj
\end{bmatrix}
$$

Coding part:

In [61]:
import numpy as np

# Create arrays for testing coding part
# Array A shape (4, 3) of random numbers 0-9
A = np.random.randint(0, 10, (4, 3))
print('Matrix A is:\n', A)

# Array B shape (3,5) of random numbers 0-9
B = np.random.randint(0, 10, (3,5))
print('Matrix B is:\n', B)

# Array C shape (4, 3) of random numbers 0-9
C = np.random.randint(0, 10, (4, 3))
print('Matrix C is:\n', C)

# Array D is an empty array
D = np.empty((0,0))
print('Matrix D is an empty array.')

print('Size of D = ', D.size)

# Function check if 2 matrices can be product
def multiply_matrices(A, B):
  # Check if A or B is an empty matrix
  if A.size == 0:
    print('There is an empty matrix!')
    return
  elif B.size == 0:
    print('There is an empty matrix!')
    return
  else:
    a = A.shape[1]
    b = B.shape[0]
  # Check if number of columns of A is equal number of rows of B
  if a == b:
    print('A and B are compatible!')
    C = np.zeros((A.shape[0], B.shape[1]))
    test = 0
    for val in C[0]:
      test = test + 1

    print(test)
  return C

  
# Testing 2 compatible matrices
multiply_matrices(A, B)

Matrix A is:
 [[1 2 7]
 [9 0 9]
 [3 1 2]
 [2 6 0]]
Matrix B is:
 [[8 8 0 8 2]
 [1 9 8 2 9]
 [9 5 7 4 6]]
Matrix C is:
 [[9 2 3]
 [1 8 7]
 [3 7 1]
 [4 8 4]]
Matrix D is an empty array.
Size of D =  0
A and B are compatible!
5


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])