<a href="https://colab.research.google.com/github/anhtel94/CAP4630---Machine-Learning/blob/master/HW_1/multiply_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 2: multiply_matrices

 Matrix A shape(m, n) and matrix B shape(i, j) are able to product and form matrix C shape(m, j) if and only if n = i and both A and B are not empty.

$$
\begin{bmatrix} 
a_11 & \cdots & a_1n \\
\vdots & \ddots & \vdots \\
a_m1 & \cdots & a_mn
\end{bmatrix}
*
\begin{bmatrix} 
b_11 & \cdots & b_1j \\
\vdots & \ddots & \vdots \\
b_i1 & \cdots & b_ij
\end{bmatrix}
=
\begin{bmatrix} 
c_11 & \cdots & c_1j \\
\vdots & \ddots & \vdots \\
c_m1 & \cdots & c_mj
\end{bmatrix}
$$

Coding part:

In [24]:
import numpy as np

# Create arrays for testing coding part
# Array A shape (4, 3) of random numbers 0-9
A = np.random.randint(0, 10, (4, 3))
print('Matrix A is:\n', A)

# Array B shape (3,5) of random numbers 0-9
B = np.random.randint(0, 10, (3,5))
print('Matrix B is:\n', B)

# Array C shape (4, 3) of random numbers 0-9
C = np.random.randint(0, 10, (4, 3))
print('Matrix C is:\n', C)

# Array D is an empty array
D = np.empty((0,0))
print('Matrix D is an empty array.')

# Function check if 2 matrices can be product
def multiply_matrices(A, B):
  # Check if A or B is an empty matrix
  if A.size == 0:
    raise Exception('These two matrices are incompatible, at least one is empty!')
    return
  elif B.size == 0:
    raise Exception('These two matrices are incompatible, at least one is empty!')
    return
  else:
    # Number of A's columns
    Ac = A.shape[1] 
    # Number of B's rows
    Br = B.shape[0]
  # Check if number of columns of A is equal number of rows of B
  if Ac == Br:
    # Number of A's rows
    Ar = A.shape[0]
    # Number of B's columns
    Bc = B.shape[1]

    C = np.zeros((Ar, Bc))
    r = 0
    c = 0
    # Loop through matrix C to calculate each element
    # Loop through rows
    for val1 in C:
      if r == Ar:
        break
      # Loop through columns
      for val2 in C[0]:
        C[r,c] = sum(np.multiply(A[r],B[:Bc, c]))
        c = c + 1
        if c == Bc:
          c = 0
          r = r + 1
          continue
  else:
    raise Exception('These two matrices are incompatible, number of columns in first matrix is different than number of rows in second matrix!')
  return C

  
# Testing 2 compatible matrices
print('\nTesting A * B')
print('A * B = \n', multiply_matrices(A, B))
# Testing 2 incompatible matrices with different size
print('\nTesting A * C')
multiply_matrices(A,C)
# Testing 2 incompatible matrices with one is empty matrix
print('\nTesting A * D')
multiply_matrices(A,D)

Matrix A is:
 [[9 2 2]
 [9 3 0]
 [1 1 0]
 [4 5 5]]
Matrix B is:
 [[7 6 2 1 3]
 [7 6 0 3 4]
 [2 8 2 1 3]]
Matrix C is:
 [[5 9 9]
 [0 9 6]
 [9 6 3]
 [1 0 5]]
Matrix D is an empty array.

Testing A * B
A * B = 
 [[81. 82. 22. 17. 41.]
 [84. 72. 18. 18. 39.]
 [14. 12.  2.  4.  7.]
 [73. 94. 18. 24. 47.]]

Testing A * C


Exception: ignored